from enum import Enum

class ResultatRuleType(Enum):
    CART_STATE = "CART_STATE"
    BASE_DISCOUNT = "BASE_DISCOUNT"
    SPECIAL = "SPECIAL ARTICLE"
    IDENTICAL_ARTICLE = "IDENTICAL ARTICLE"
    CLEARANCE_ARTICLE = "CLEARANCE ARTICLE"
    CEILING_DISCOUNT = "CEILING_DISCOUNT"